branches:
  only:
  - master
language: node_js
node_js:
- stable
cache:
  directories:
  - "$HOME/.yarn-cache"
env:
  global:
  - GH_REF: github.com/iCHEF/ichef-squarespace-scripts
  - secure: Tc0G5cxVizJLZRg9IOrvtpDjtFzyIQmizmrHIwbKSmwZn1YpQuTbxG+lgRsYhr//+YES7rfzaNGIG2k2aQaD2HYV4HTE40i4ZcODM5Top9GFkm1+CVi15n8kFHOpoU2VwATJZS74qwujKYFk/vcQmWGERLTr72HHVl7N3OpHGIg9zfXR+zKpRSVn1cEetl1jAnMPoVBp3jJCVTbTtLQXpl/q36lY2cVFNPP+kXNE76pxWtZOlWifF7yEN5ayf1zG+l8RuOQSVsvE5bCcqq7cQ12/3b6RRz4uGlpVz0nZnuVuiD1Jt89r8+1Xy1AQsjs9/q8nllKhPv3RMFr9i4r0HZjba0L0eUFj6m80GSs7px7jQXqP4vpv1PNArMyD/FTwuYfUGKI22RF67zWhFmtJB4OtfvmgwHOB7FQhhouactzjMCpZDytB3FqXzrHhZ0wwaW3pIEl+ljM1lZay0/aExxc+mjGMN3zlOUP8I/1O0Kmg38ib73WADdzYO/UCQKQRr38nDcSblWLThtaCU9c6Lb0jLOvwdjOrzA6RsW4OUJY7VgnOnatT2G1++YTmfTFzwyhcr+nVb+tMmF841S1Qs+FqqDoI6WCQtZpmJkozbpzHO+tKemtq9/dJnjD7El9t62PLppN4i7XFfEneQPKmDhyW9GPhPC4g0dWmMOt5lh4=
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install:
- yarn
script:
- npm run build
- bash deploy.sh
